name: "Update stock data everyday"

on:
  workflow_dispatch:
  schedule:
    -   cron: "30 4 * * *"
    -   cron: "45 7 * * *"

jobs:
  export-jpegs:
    runs-on: ubuntu-latest
    name: Export JPEGs
    timeout-minutes: 30
    steps:
      -   uses: actions/checkout@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
      -   name: Set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: 3.12
      -   name: Setup dependencies
          run: pip install -r requirements.txt
      -   name: Remove old jpg
          run: rm images/*.jpg
      -   name: Run export jpg
          run: python main.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto Update"
          git push
